{
 "title": "Catalogix Service Health",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pod Restarts (Namespace - catalogix)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"catalogix\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency p95 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"catalogix\"}[5m])) by (le, service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (up{namespace=\"catalogix\", service=~\".*\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Traffic (req/s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"catalogix\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_server_requests_seconds_count{status=~\"5..\", namespace=\"catalogix\"}[5m])) by (service)\r\n  OR\r\n  (sum(rate(http_server_requests_seconds_count{namespace=\"catalogix\"}[5m])) by (service) * 0)\r\n)\r\n/\r\nsum(rate(http_server_requests_seconds_count{namespace=\"catalogix\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"catalogix\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}