# Enable when autoscaling is needed
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-svc-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-svc
  minReplicas: {{ .Values.userSvc.hpa.minReplicas }}
  maxReplicas: {{ .Values.userSvc.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.userSvc.hpa.cpuUtilization }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-svc-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-svc
  minReplicas: {{ .Values.productSvc.hpa.minReplicas }}
  maxReplicas: {{ .Values.productSvc.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.productSvc.hpa.cpuUtilization }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-svc-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-svc
  minReplicas: {{ .Values.frontendSvc.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontendSvc.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontendSvc.hpa.memoryUtilization }}
{{- end }}