plugins:
  - name: docker-workflow

  # CORE
  - name: configuration-as-code
  - name: matrix-auth
  - name: credentials
  - name: credentials-binding

  # PIPELINES
  - name: workflow-aggregator
  - name: pipeline-stage-view

  # SCM
  - name: git
  - name: github

  # JOB DSL
  - name: job-dsl

  # TOOLS
  - name: nodejs
  - name: maven-plugin

  # SONAR
  - name: sonar

  # AWS
  - name: aws-credentials

  # UTILS
  - name: timestamper
  - name: ws-cleanup
