plugins:
  - id: docker-workflow

  # CORE
  - id: configuration-as-code
  - id: matrix-auth
  - id: credentials
  - id: credentials-binding

  # PIPELINES
  - id: workflow-aggregator
  - id: pipeline-stage-view

  # SCM
  - id: git
  - id: github

  # JOB DSL
  - id: job-dsl

  # TOOLS
  - id: nodejs
  - id: maven-plugin

  # SONAR
  - id: sonar

  # AWS
  - id: aws-credentials

  # UTILS
  - id: timestamper
  - id: ws-cleanup
